# SPDX-FileCopyrightText: © 2023 Kevin Meagher
#
# SPDX-License-Identifier: CC0-1.0

# format = "yyyy-MM-dd HH:mm:ss Z"
locale = "en_US"
zones = [
  "Pacific/Auckland",
  "Australia/Adelaide",
  "Asia/Tokyo",
  # "Europe/London",
  "Europe/Berlin",
  "America/New_York",
  # "America/Chicago",
  "America/Los_Angeles",
]

[aliases]
"Australia/Adelaide" = "Adelaide"
"America/Chicago" = "US Central"
"America/Los_Angeles" = "US Pacific"
"America/New_York" = "US Eastern"
"Asia/Tokyo" = "Japan/Korea"
"Europe/Berlin" = "Central Europe"
"Pacific/Auckland" = "New Zealand"
"GMT" = "United Kingdom"

[localtime]
attrs = ["bold"]
color = "red"

[reftime]
attrs = ["bold"]
color = "cyan"
